### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by gedw99** [ccutch/pb-j-stack#1]
Is there something wrong with user login ? when I click login its hits the server but does nothing.

1. Change hardcoded path on Login page to correct local server: https://github.com/ccutch/pb-j-stack/blob/main/templates/pages/login.html#L3C31-L3C31 

```js
//const pb = new PocketBase('https://8090-ccutch-pbjstack-tcrrn613x9y.ws-us105.gitpod.io');
  const pb = new PocketBase('http://127.0.0.1:8090');
```

2. go run . and Create the admin, and then create a user via the PB GUI.

3. Open http://127.0.0.1:8090, and login with user details.

4. Check error at http://127.0.0.1:8090/_/#/logs

```
Status | 404
Method | POST
Auth | guest
URL | /api/api/admins/auth-with-password
Referer | http://127.0.0.1:8090/
Remote IP | 127.0.0.1
User IP | 127.0.0.1
UserAgent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Meta | {   "errorDetails": "<nil>",   "errorMessage": "Not Found" }
Created | 2023-11-1608:48:00 UTC
```

**Comment by ccutch** [comment]
Thank you, updated to use the window location origin :)
